ALTER TABLE `University`
ADD COLUMN `ranking_national_usnews` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_national_washington_monthly` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_global_qs` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_global_times` SMALLINT(4) NOT NULL,
ADD COLUMN `major_1` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `major_2` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `major_3` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `major_4` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `ranking_major_national_1` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_national_2` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_national_3` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_national_4` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_global_1` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_global_2` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_global_3` SMALLINT(4) NOT NULL,
ADD COLUMN `ranking_major_global_4` SMALLINT(4) NOT NULL,
ADD COLUMN `brief_introduction` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `student_size_undergrad` INT(8) NOT NULL,
ADD COLUMN `student_size_grad` INT(8) NOT NULL,
ADD COLUMN `student_size_total` INT(8) NOT NULL,
ADD COLUMN `student_size_freshman` INT(8) NOT NULL,
ADD COLUMN `student_size_male_female_ratio` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `student_faculty_ratio` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `average_class_size` INT(8) NOT NULL,
ADD COLUMN `retention_rate` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `toefl_score_min` SMALLINT(4) NOT NULL,
ADD COLUMN `toefl_score_recommended` SMALLINT(4) NOT NULL,
ADD COLUMN `toefl_score_reading` SMALLINT(4) NOT NULL,
ADD COLUMN `toefl_score_writing` SMALLINT(4) NOT NULL,
ADD COLUMN `toefl_score_listening` SMALLINT(4) NOT NULL,
ADD COLUMN `toefl_score_speaking` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_25_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_75_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_cr_25_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_cr_75_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_writing_25_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_writing_75_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_math_25_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `sat_math_75_percentile` SMALLINT(4) NOT NULL,
ADD COLUMN `recommended_courses` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `admission_rate` DECIMAL(5,2) NOT NULL,
ADD COLUMN `admission_rate_international` DECIMAL(5,2) NOT NULL,
ADD COLUMN `ea_deadline` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `ed1_deadline` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `ed2_deadline` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `rea_deadline` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `rd_deadline` VARCHAR(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `common_app_system` TINYINT(1) NOT NULL,
ADD COLUMN `essay_prompts_1` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `essay_prompts_2` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `essay_prompts_3` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `essay_prompts_4` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `essay_prompts_5` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
ADD COLUMN `waitlist_no_of_waitlisted_student` INT(8) NOT NULL,
ADD COLUMN `waitlist_admitted_off_waitlist` INT(8) NOT NULL,
ADD COLUMN `waitlist_rate_of_getting_off_waitlist` DECIMAL(5,2) NOT NULL;
